name: tile2vec
channels:
- conda-forge
- defaults
dependencies:
- boost=1.66.0=py36_1
- boost-cpp=1.66.0=1
- bzip2=1.0.6=1
- cairo=1.14.10=0
- curl=7.55.1=0
- dbus=1.10.22=0
- freetype=2.8.1=0
- freexl=1.0.4=0
- gdal=2.2.3=py36_0
- geos=3.6.2=1
- geotiff=1.4.2=1
- gettext=0.19.8.1=0
- giflib=5.1.4=0
- glib=2.55.0=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- hdf4=4.2.13=0
- hdf5=1.10.1=2
- json-c=0.12.1=0
- kealib=1.4.7=4
- krb5=1.14.2=0
- libdap4=3.18.3=2
- libgdal=2.2.3=3
- libiconv=1.15=0
- libkml=1.3.0=6
- libnetcdf=4.4.1.1=10
- libpq=9.6.3=0
- libspatialite=4.3.0a=19
- libssh2=1.8.0=2
- libtiff=4.0.9=0
- openjpeg=2.3.0=2
- pixman=0.34.0=1
- poppler=0.61.1=3
- poppler-data=0.4.8=0
- proj4=4.9.3=5
- qt=5.6.2=7
- sqlite=3.20.1=0
- xerces-c=3.2.0=0
- bleach=2.1.2=py36_0
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2018.1.18=py36_0
- cycler=0.10.0=py36h93f1223_0
- decorator=4.2.1=py36_0
- entrypoints=0.2.3=py36h1aec115_2
- expat=2.2.5=he0dffb1_0
- fontconfig=2.12.4=h88586e7_1
- gmp=6.1.2=h6c8ec71_1
- html5lib=1.0.1=py36h2f9c1c0_0
- icu=58.2=h9c2bf20_1
- intel-openmp=2018.0.0=hc7b2577_8
- ipykernel=4.8.2=py36_0
- ipython=6.2.1=py36h88c514a_1
- ipython_genutils=0.2.0=py36hb52b0d5_0
- ipywidgets=7.1.2=py36_0
- jedi=0.11.1=py36_0
- jinja2=2.10=py36ha16c418_0
- jpeg=9b=h024ee3a_2
- jsonschema=2.6.0=py36h006f8b5_0
- jupyter=1.0.0=py36_4
- jupyter_client=5.2.2=py36_0
- jupyter_console=5.2.0=py36he59e554_1
- jupyter_core=4.4.0=py36h7c827e3_0
- kiwisolver=1.0.1=py36h764f252_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran=3.0.0=1
- libgfortran-ng=7.2.0=h9f7466a_2
- libpng=1.6.34=hb9fc6fc_0
- libsodium=1.0.15=hf101ebd_0
- libstdcxx-ng=7.2.0=h7a57d05_2
- libxcb=1.12=hcd93eb1_4
- libxml2=2.9.7=h26e45fe_0
- markupsafe=1.0=py36hd9260cd_1
- matplotlib=2.2.0=py36hbc4b006_0
- mistune=0.8.3=py36_0
- mkl=2018.0.1=h19d6760_4
- nbconvert=5.3.1=py36hb41ffb7_0
- nbformat=4.4.0=py36h31c9010_0
- ncurses=6.0=h9df7e31_2
- notebook=5.4.0=py36_0
- numpy=1.14.1=py36h3dfced4_1
- openssl=1.0.2n=hb7f436b_0
- pandas=0.22.0=py36hf484d3e_0
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py36ha6701b7_1
- parso=0.1.1=py36h35f843b_0
- patsy=0.5.0=py36_0
- pcre=8.41=hc27e229_1
- pexpect=4.4.0=py36_0
- pickleshare=0.7.4=py36h63277f8_0
- pip=9.0.1=py36_5
- prompt_toolkit=1.0.15=py36h17d85b1_0
- ptyprocess=0.5.2=py36h69acd42_0
- pygments=2.2.0=py36h0d3125c_0
- pyparsing=2.2.0=py36hee85983_1
- pyqt=5.6.0=py36h0386399_5
- python=3.6.4=hc3d631a_1
- python-dateutil=2.6.1=py36h88d3b88_1
- pytz=2018.3=py36_0
- pyzmq=16.0.3=py36he2533c7_0
- qtconsole=4.3.1=py36h8f73b5b_0
- readline=7.0=ha6073c6_4
- scikit-learn=0.19.1=py36h7aa7ec6_0
- scipy=1.0.0=py36hbf646e7_0
- seaborn=0.8.1=py36hfad7ec4_0
- send2trash=1.5.0=py36_0
- setuptools=38.5.1=py36_0
- simplegeneric=0.8.1=py36_2
- sip=4.18.1=py36h51ed4ed_2
- six=1.11.0=py36h372c433_1
- statsmodels=0.8.0=py36h8533d0b_0
- terminado=0.8.1=py36_1
- testpath=0.3.1=py36h8cadb63_0
- tk=8.6.7=hc745277_3
- tornado=5.0=py36_0
- traitlets=4.3.2=py36h674d592_0
- util-linux=2.21=0
- wcwidth=0.1.7=py36hdf4376a_0
- webencodings=0.5.1=py36h800622e_1
- wheel=0.30.0=py36hfd4bba0_1
- widgetsnbextension=3.1.4=py36_0
- xz=5.2.3=h55aa19d_2
- zeromq=4.2.2=hbedb6e5_2
- zlib=1.2.11=ha838bed_2
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15

